### ISSUE TITLE
Kirstie's To Do list - Week starting 13th November 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#106]
## URGENT
- [ ] Teaching - reply to expectations postits

#### Emails/Online
- [ ] Email CH re FA
- [ ] Email SV re TFL data study group/hackathon
- [ ] Email psychiatry dude from CamNeuro NNHD
- [ ] Email FV & MOR re: building interactive version of r code
- [ ] Send pictures from China & thank you emails

#### Paperwork
- [ ] Invoice to British Library
- [ ] Invoice to Fuel

#### Turing Community
- [ ] Summary & next steps for research fellows office hours -- see #81 
- [ ] Reproducible research summary email to students (& wider)
- [ ] Organise RR office hours - Friday at 1pm
- [ ] Make RR repo
- [ ] Paragraph about importance of open source for website

#### Whitaker Lab website/github
- [ ] Add ICON2017 slides to whitakerlab.github.io
- [ ] Add CamNeuro Data Blitz & NNHD to whitaker lab blog
- [ ] Add talk for Online Brain Intensive to website
- [ ] Add ECNP talk to website
- [ ] Add OSIP & OSET talks to website -- http://go.epfl.ch/aFD, https://library.epfl.ch/open-science-evening-talks
- [ ] Blog post about how to run a data blitz
- [ ] Update Whitakerlab onboarding

#### Outreach
- [ ] DBS check with [STEM Ambassadors](https://www.stem.org.uk/stem-ambassadors/ambassadors)
- [ ] Submit reimbursement receipts
- [ ] Share pictures on slack

#### NSPN Analyses
- [ ] Figure our running SW's code
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good

#### NSPN Data Management ([issue list](https://github.com/TeamNSPN/DataManagement/issues))
- [ ] Update data management team on Cambridge repository -- see [NSPN-DM-#1](https://github.com/TeamNSPN/DataManagement/issues/1)
- [ ] Add replies to email questions w GP & LV to repo
- [ ] Add to issues in [DataManagement](https://github.com/TeamNSPN/DataManagement) repo 
- [ ] Create agenda for next meeting
- [ ] Send minutes from last meeting

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Comments on grant w AV
- [ ] Comments on grant w LR

#### Invited talks/teaching
- [ ] Talk for Warsaw brainhack -- see #80 
  - [ ] Pick battle song for before the talk!
- [ ] Slides for Engaging Researchers in Good Data Management in Cambridge

#### BrainAge
- [ ] Write code to compare a bunch of different models

#### OpenConCam
- [ ] Bit more promotion
- [ ] Coordinate live blogging posts

### Peer Reviews
- [ ] A0026
- [ ] 

### MozFest
- [ ] Thank you emails - team & facilitators

### OHBM
- [ ] OpenScience github repo
- [ ] Guide for rotating curation of slack
- [ ] Proposal for monthly demos

### Turing Data Study group
- [ ] Write up tasks that need to be distributed to challenge teams 
- [ ] Investigate use of github for project management
  - [ ] Create github repository templates for projects to support the teams
- [ ] Write a code of conduct and expectations guidelines

### BIDS
- [ ] Reply to emails re: making more welcoming & updating website
- [ ] Update on singularity [see issue #142](https://github.com/singularityware/singularityware.github.io/issues/142#issuecomment-341777852)

#### DAS
- [ ] Assign articles to ontology
- [ ] Create descriptive plots
