### ISSUE TITLE
Kirstie's TO DO list - week starting 8th May 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#18]
#### Emailing/online
- [x] Send back COI for Bea's paper
- [x] Submit MPhil feedback
- [ ] Set up site for Mozilla Global sprint in SF
- [x] Give feedback on fellowship application
- [x] Reply to summer school invite
- [ ] Reach out to internship supervisors re: microWOW for interns
  - [ ] Send 2-3 sentence description and title to Emma & Emily
- [x] Recruit more submissions for gift
- [ ] Apply for data for the [fragile families challenge](https://whitakerlab.github.io/resources/)
- [ ] Upload RK's code & data to Cambridge repository
- [x] Find code for visualising behavioural networks
- [x] Feedback for K's application
- [x] Feedback on Bruno's blog post
- [ ] Book travel & accommodation
  * Lon to SF
  * LA to CT
  * CT to YVR
  * YVR to Lon
- [ ] Find time to chat w LC from OpenCon
- [ ] Find time for OHBM SIG meeting
- [x] Register for Biological Psychiatry conference 
- [x] Feedback on Bruno's blog post
- [x] Feedback on K's application

#### In person
- [ ] Drop off cash for retirement & sign card

#### Peer reviews
- [x] A0024
- [ ] A0025

#### Presentations
- [ ] Poster for Cam BrainFest - see #23 
- [ ] Talk for Biological Psychiatry conf

#### Blogs
- [ ] MQ blog
- [ ] Visit to Penn & Science March blog
- [ ] Story Engine for Mozilla
- [x] Mozilla fellowship
  - [x] On Mozilla Science lab website
- [ ] New preprints - Jakob and Frantisek's
  * http://biorxiv.org/content/early/2017/05/09/135855
  * http://biorxiv.org/content/early/2017/04/12/126920

#### Documentation
- [ ] Write up documentation for how to access data from NSPN paper
  - [ ] Fix email address in current documentation (should be: openNSPN@medschl.cam.ac.uk)

#### Data wrangling
- [ ] Update table of participants for NSPN & assoc studies
- [ ] Process all scans - see #17 
- [ ] Wrangle data into a nicer format - see #22

#### OpenConCam
- [ ] Need a theme - see [OCC2017, issue 11](https://github.com/OpenConCam/OpenConCam/issues/11)
- [ ] Write up last year's meeting as a [report in RIO](http://www.opencon2017.org/publishing_a_workshop_report_for_your_satellite_event_in_rio_journal) - see [OCC2017, issue 18](https://github.com/OpenConCam/OpenConCam/issues/19)

**Comment by KirstieJane** [comment]
Feedback on Bruno's blog post

**Comment by KirstieJane** [comment]
Build up WOW for Amsterdam, Turing and OHBM Brainhack

**Comment by KirstieJane** [comment]
Expenses for Mozilla - travel to Penn, microWOW and laptop

**Comment by KirstieJane** [comment]
Closed with 14 of 37 check boxes ticked 🌮
