### ISSUE TITLE
Admin tasks for Turing Way

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#220]
- [x] Make doodle for Feb sprint https://github.com/alan-turing-institute/the-turing-way/issues/138
- [x] Add folks to Turing slack https://github.com/alan-turing-institute/the-turing-way/issues/127
- [x] Add folks to Turing github https://github.com/alan-turing-institute/the-turing-way/issues/143
