### ISSUE TITLE
Plans for Georgia | 17 to 23 June

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#273]
### Autistica visit to Turing

- [x] Send slides to JC and CL to compile slides together and check on running order etc

### Call w stakeholders

- [x] How involved in Discover conf? Maybe part of breakfast?
  * PR to github repo (once we have ethics confirmed) rather than slides

### Funding reports

- [x] Submit quarterly updates to Health programme - deadline 17 June
- [x] Turing project website - quick check on 1st vs 3rd person - then all ready to submit!
- [x] Submit annual update to Autistica - deadline 30 June
  * @GeorgiaHCA should now have access via Research Fish 🐟 🐠 🐟 

### Roadmap

- [ ] Exciting times - developing a roadmap for OH, ML & F to work together 👾 

### Position paper

- [x] Incorporate feedback into the values section of the paper

## Actions for Kirstie

- [x] Introduce to policy team
- [x] Review intro blog

**Comment by KirstieJane** [comment]
Awesome! Well done :rocket:
