### ISSUE TITLE
Kirstie's TO DO list - week starting 15th May 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#28]
#### Emailing/online
- [x] Set up site for Mozilla Global sprint in ~SF~ Mountain View
  - [x] Register and promote
- [ ] Reach out to internship supervisors re: microWOW for interns
  - [ ] Send 2-3 sentence description and title to Emma & Emily
- [x] Apply for data for the [fragile families challenge](http://www.fragilefamilieschallenge.org/apply/)
  - [ ] Send out email about meeting on Wednesday
- [ ] Upload code & data to Cambridge repository
  * Rogier
  * Anne-Laura
- [x] Book travel & accommodation
  * Lon to SF
  * LA to CT
  * CT to YVR
  * YVR to Lon
- [x] Send in paperwork for OHBM travel award
- [ ] Find time to chat w LC from OpenCon
- [x] Find time for OHBM SIG meeting
- [ ] Expenses for Mozilla - travel to Penn, microWOW and laptop
- [x] Book OpenConCam meeting for 23rd May and first tuesday of the month til December
- [x] Register for ICON 
- [x] Bio for Gay UK event
- [x] Travel award paperwork for OHBM hackathon
- [x] Book flights for Lausanne trip

#### In person
- [ ] Drop off cash for retirement & sign card

#### Peer reviews
- [ ] A0025

#### Presentations
- [ ] Poster for Cam BrainFest - see #23 
- [x] Talk for Biological Psychiatry conf

#### Blogs
- [ ] MQ blog
- [ ] Visit to Penn & Science March blog
- [ ] SOBP blog
- [ ] Story Engine for Mozilla
- [ ] New preprints - Jakob and Frantisek's
  * http://biorxiv.org/content/early/2017/05/09/135855
  * http://biorxiv.org/content/early/2017/04/12/126920
- [ ] Apply to [OpenCon](http://www.opencon2017.org/) (Update: not open yet - whoops!) 
  - [x] Upload 2016 application

#### WOW
- [ ] Build up WOW for Amsterdam, Turing and OHBM Brainhack

#### NSPN Data Sharing
- [ ] Write up documentation for how to access data from NSPN paper
  - [ ] Fix email address in current documentation (should be: openNSPN@medschl.cam.ac.uk)
- [ ] Get information up on [NSPNTeam](https://github.com/TeamNSPN/DataManagement) repository

#### Data wrangling
- [ ] Update table of participants for NSPN & assoc studies
- [ ] Process all scans - see #17 
- [ ] Wrangle data into a nicer format - see #22

#### OpenConCam
- [ ] Need a theme - see [OCC2017, issue 11](https://github.com/OpenConCam/OpenConCam/issues/11)
- [ ] Write up last year's meeting as a [report in RIO](http://www.opencon2017.org/publishing_a_workshop_report_for_your_satellite_event_in_rio_journal) - see [OCC2017, issue 18](https://github.com/OpenConCam/OpenConCam/issues/19)

#### Applications
- [ ] [Allen Inst](http://www.alleninstitute.org/what-we-do/brain-science/about/advisors/next-generation-leaders/)
- [ ] Turing and MozFest privacy event

**Comment by KirstieJane** [comment]
Make abstract and talk for Poldrack lab visit

Email AG w info on visit

Email BIDS re visit

Email CM re visit

**Comment by KirstieJane** [comment]
Closed with 13 of 39 done (aaaaah :weary:)
