### ISSUE TITLE
Plans for Georgia | 13 to 21 August

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#289]
### Actions for Georgia

- [ ] Get excited about wireframes - https://github.com/alan-turing-institute/AutisticaCitizenScience/issues/23
- [ ] Organise focus groups https://github.com/alan-turing-institute/AutisticaCitizenScience/issues/22
- [ ] Make changes to processes based on feedback https://github.com/alan-turing-institute/AutisticaCitizenScience/issues/24
- [ ] Open pull requests for lab meeting and "meet 3 people" blog posts

### Actions for Kirstie

- [ ] Read and given comments on position paper

**Comment by GeorgiaHCA** [comment]
Next - wireframes :) ! I'm already excited
