### ISSUE TITLE
Kirstie's TO DO list - week starting 22nd May 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#36]
#### Emailing/online
- [ ] Reach out to internship supervisors re: microWOW for interns
  - [x] Send 2-3 sentence description and title to Emma & Emily
- [x] Apply for data for the [fragile families challenge](http://www.fragilefamilieschallenge.org/apply/)
  - [x] Send out email about meeting on Wednesday
   - [ ] Fragile families email to team re meetings in June and July
- [ ] Upload code & data to Cambridge repository
  * Rogier
  * Anne-Laura
- [ ] Book/organise accommodation
  * SF/Berkeley/Mountain View
  * Cape Town
  * Vancouver
- [ ] Find time to chat w LC from OpenCon
- [ ] Expenses for Mozilla - travel to Penn, microWOW and laptop, airbnb in Mountain View
- [x] Email abstract for talk at Stanford
- [ ] Email AG w info on visit
- [x] Email BIDS re visit
- [x] Email CM re visit
- [x] Review IS pull request - see #19
- [x] Send mentoring resources to MV

#### In person
- [x] Drop off cash for retirement & sign card

#### Peer reviews
- [x] A0025

#### Presentations
- [ ] Poster for Cam BrainFest - see #23 
- [ ] Talk for visit to Poldrack lab

#### Blogs
- [ ] MQ blog
- [ ] Visit to Penn & Science March blog
- [ ] SOBP blog
- [ ] Story Engine for Mozilla
- [ ] New preprints - Jakob and Frantisek's
  * http://biorxiv.org/content/early/2017/05/09/135855
  * http://biorxiv.org/content/early/2017/04/12/126920
- [ ] Apply to [OpenCon](http://www.opencon2017.org/) (Update: not open yet - whoops!) 
  - [x] Upload 2016 application

#### WOW
- [ ] Build up WOW for Amsterdam, Turing and OHBM Brainhack

#### NSPN Data Sharing
- [x] Write up documentation for how to access data from NSPN paper
  - [x] Fix email address in current documentation (should be: openNSPN@medschl.cam.ac.uk)
- [x] Get information up on [NSPNTeam](https://github.com/TeamNSPN/DataManagement) repository

#### Data wrangling
- [ ] Update table of participants for NSPN & assoc studies
- [ ] Process all scans - see #17 
- [ ] Wrangle data into a nicer format - see #22

#### OpenConCam
- [ ] Need a theme - see [OCC2017, issue 11](https://github.com/OpenConCam/OpenConCam/issues/11)
- [ ] Write up last year's meeting as a [report in RIO](http://www.opencon2017.org/publishing_a_workshop_report_for_your_satellite_event_in_rio_journal) - see [OCC2017, issue 18](https://github.com/OpenConCam/OpenConCam/issues/19)

#### Applications
- [ ] [Allen Inst](http://www.alleninstitute.org/what-we-do/brain-science/about/advisors/next-generation-leaders/)
- [ ] Turing and MozFest privacy event

**Comment by KirstieJane** [comment]
Send mentorship resources to MV

**Comment by KirstieJane** [comment]
Fragile families email to all

**Comment by KirstieJane** [comment]
Issue closed on 30th May with 14 of 37 items complete
