### ISSUE TITLE
Kirstie's TO DO list - week starting 29th May 2017 

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#41]
#### Emailing/online
- [ ] Reach out to internship supervisors re: microWOW for interns
  - [ ] Send outline of schedule to Emma & Emily
- [ ] Fragile families email to team re meetings in June and July
- [ ] Upload code & data to Cambridge repository
  * Rogier
  * Anne-Laura
- [ ] Book/organise accommodation
  * Cape Town
  * Vancouver
- [ ] Find time to chat w LC from OpenCon
- [ ] Expenses for Mozilla - travel to Penn, microWOW and laptop, airbnb in Mountain View
- [ ] Email AG w info on visit

#### Presentations
- [ ] Poster for Cam BrainFest - see #23 
- [ ] Talk for visit to Poldrack lab

#### Blogs
- [ ] MQ blog
- [ ] Visit to Penn & Science March blog
- [ ] SOBP blog
- [ ] Story Engine for Mozilla
- [ ] New preprints - Jakob and Frantisek's
  * http://biorxiv.org/content/early/2017/05/09/135855
  * http://biorxiv.org/content/early/2017/04/12/126920
- [ ] Apply to [OpenCon](http://www.opencon2017.org/) (Update: not open yet - whoops!) 

#### WOW
- [ ] Build up WOW for Amsterdam, Turing and OHBM Brainhack

#### NSPN Data Sharing
- [ ] Follow up with repository re: data access
- [ ] Figure out what's needed for PI meeting

#### Data wrangling
- [ ] Update table of participants for NSPN & assoc studies
- [ ] Process all scans - see #17 
- [ ] Wrangle data into a nicer format - see #22

#### OpenConCam
- [ ] Need a theme - see [OCC2017, issue 11](https://github.com/OpenConCam/OpenConCam/issues/11)
- [ ] Write up last year's meeting as a [report in RIO](http://www.opencon2017.org/publishing_a_workshop_report_for_your_satellite_event_in_rio_journal) - see [OCC2017, issue 18](https://github.com/OpenConCam/OpenConCam/issues/19)

#### Applications
- [ ] [Allen Inst](http://www.alleninstitute.org/what-we-do/brain-science/about/advisors/next-generation-leaders/)
- [ ] Turing and MozFest privacy event
