### ISSUE TITLE
Kirstie's TO DO list - week starting 24th July 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#67]
#### Emails/Online
- [ ] Arrange meeting with HQ re: Turing policy work
- [x] Read around Turing & brain for panel event - ***deadline 24th July***
- [x] Accomodation & travel for ICON2017 - Amsterdam
- [ ] Accomodation & travel for ECNP2017 - Paris
- [ ] Send Ed info on [Impact Story](https://impactstory.org/) 
- [x] Info to OHBM student/postdoc SIG
- [ ] Letters of recommendation for SRA application ***deadline 26th July***
- [x] Register for [Cam Neural Networks](http://www.neuroscience.cam.ac.uk/events/event.php?permalink=11dc77ab92) & promote at Turing

#### NSPN
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
      * **UPDATE** 13/7: this is currently underway for `UCHANGE` directory
  - [ ] Also need to check that everything looks good
- [ ] Write RA job description ***deadline 21st July***
- [ ] Update data management team on Cambridge repository

#### Blogs/interviews/writing
- [ ] 250 words on challenges & solutions for open science for OHBM Conversation piece ***deadline 25th July***
- [ ] Edit story engine for Mozilla
- [ ] Blog telling people to apply for OpenCon, Moz Open Leadership & MozFest

#### Invited talks
- [ ] Bio/abstract for talk at EPFL library 
- [ ] Abstract & visa information for ICHBD 
- [ ] Make talk for ICON (and [online brain intensive](https://www.onlinebrainintensive.com/)) - See #65 

#### Fragile Families
- [ ] Send email about meeting on Wednesday
  * Didn't do 🙄 ...but could do for next week! 

#### BrainAge
- [ ] Get code installed & running
- [ ] Send questions to FL

#### OpenAdvice
- [ ] Migrate to organisation [ProjectOpenAdvice](https://github.com/ProjectOpenAdvice/projectopenadvice.github.io) & build website there: https://projectopenadvice.github.io/
- [ ] Merge jekyll pull request

#### OpenConCam
- [x] Summary email from OpenConCam meeting
- [ ] Add speakers to thread [OpenConCam/issues/16](https://github.com/OpenConCam/OpenConCam/issues/16)
- [ ] Add budget info to thread [OpenConCam/issues/16](https://github.com/OpenConCam/OpenConCam/issues/18)
- [ ] Move speakers to google doc & email around

**Comment by KirstieJane** [comment]
Closing with BILLIONS OF THINGS NOT DONE! GAAAAAH 😭
