### ISSUE TITLE
Kirstie's TO DO list - week starting 14th August 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#75]
## URGENT
- [ ] Letters of recommendation for SRA application ***deadline 26th July***
- [ ] Write RA job description ***deadline 21st July***

#### Emails/Online
- [x] Review 50 OpenCon applications
  * 40/50 done 🙌  10/50 to go 😧 
- [ ] Email NCH re inclusivity call
- [ ]  Add ICON2017 slides to whitakerlab.github.io
- [ ] Add quote to Mozilla retreat google doc
  *"Why is Internet health such an important issue for humanity? Why do we each do this work? Why is it urgent?"*
- [x] Edit IS email & report
- [ ] Reply to PB email about  outreach
- [x] Prep for meeting w CM - personality & memory models
- [ ] Introduce HQ to CSAP folk & Inga
- [ ] Read Turing challenges etc
- [ ] Complete Turing Challenges survey
- [x] Schedule call w Wellcome Trust
- [x] Reply to SK re: licensing for brain intensive videos
- [x] Feedback re brown bag
- [ ] Invoice to British Library
- [ ] Invoice to Fuel
- [ ] Newsletter - August #74 
- [ ] Newsletter - September #78 

#### NSPN
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
      * **UPDATE** 13/7: this is currently underway for `UCHANGE` directory
  - [ ] Also need to check that everything looks good
- [ ] Incorporate [von Economo atlas](http://www.dutchconnectomelab.nl/economo/) in NSPN code
- [ ] Send HCP parcellation data to JS ***deadline 1st August***
- [ ] Update data management team on Cambridge repository
- [ ] Email to SW & PV re analysis update
- [ ] Arrange date for next data management meeting

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Call for evidence -- see #76 
- [ ] Research report for Turing -- see #69  ***deadline 22nd August***
- [ ] Apply for rOpenSci fellowship -- see #66 ***deadline 1st September***

#### Invited talks
- [ ] Talk for brainintensive -- see #65 
- [x] Abstract & bio for Brainhack Warsaw
- [x] Updated abstract for Lausanne summer school

#### Fragile Families
- [ ] Send email about close of competition

#### BrainAge
- [ ] Get code installed & running
- [ ] Send questions to FL

#### OpenAdvice
- [ ] Migrate to organisation [ProjectOpenAdvice](https://github.com/ProjectOpenAdvice/projectopenadvice.github.io) & build website there: https://projectopenadvice.github.io/
- [ ] Merge jekyll pull request

#### OpenConCam
- [ ] Rearrange meeting & make to do list

### Peer Reviews
- [ ] A0029 ***deadline August 29th***
- [ ] A0030 ***deadline August 30th***

### MozFest
- [ ] Read through spreadsheet & categorise

**Comment by KirstieJane** [comment]
Closed with billions (as usual) left to do 🙄
