### ISSUE TITLE
Kirstie's To Do list - Week starting 21st August 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#82]
## URGENT
- [ ] Letters of recommendation for SRA application ***deadline 26th July***
- [ ] Write RA job description ***deadline 21st July***

#### Emails/Online
- [ ] Email NCH re inclusivity call
- [ ]  Add ICON2017 slides to whitakerlab.github.io
- [ ] Reply to PB email about  outreach
- [ ] Introduce HQ to CSAP folk & Inga
- [ ] Complete Turing Challenges survey
- [ ] Schedule call w Wellcome Trust
- [ ] Invoice to British Library
- [ ] Invoice to Fuel
- [ ] Newsletter - August #74 
- [ ] Newsletter - September #78 
- [x] Join eCOST (ICNF)

#### NSPN
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good
- [ ] Incorporate [von Economo atlas](http://www.dutchconnectomelab.nl/economo/) in NSPN code
- [ ] Send HCP parcellation data to JS ***deadline 1st August***
- [ ] Update data management team on Cambridge repository
- [ ] Email to SW & PV re analysis update
- [ ] Arrange date for next data management meeting
- [x] Upload data for TH

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Call for evidence -- see #76 
- [ ] Research report for Turing -- see #69  ***deadline 22nd August***
- [ ] Apply for rOpenSci fellowship -- see #66 ***deadline 1st September***

#### Invited talks
- [ ] Talk for brainintensive -- see #65 

#### BrainAge
- [ ] Get code installed & running
- [ ] Send questions to FL

#### OpenAdvice
- [ ] Migrate to organisation [ProjectOpenAdvice](https://github.com/ProjectOpenAdvice/projectopenadvice.github.io) & build website there: https://projectopenadvice.github.io/
- [ ] Merge jekyll pull request

#### OpenConCam
- [ ] Rearrange meeting & make to do list

### Peer Reviews
- [ ] A0029 ***deadline August 29th***
- [ ] A0030 ***deadline August 30th***

### MozFest
- [ ] Read through spreadsheet & categorise

**Comment by KirstieJane** [comment]
Closed with, as always, billions of things to do 😀
