### ISSUE TITLE
Kirstie's To Do list - Week starting 28th August 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#83]
## URGENT
- [ ] Letters of recommendation for SRA application ***deadline 26th July***

#### Emails/Online
- [ ] Email NCH re inclusivity call
- [ ] Add ICON2017 slides to whitakerlab.github.io
- [ ] Reply to PB email about  outreach
- [ ] Introduce HQ to CSAP folk & Inga
- [ ] Schedule call w Wellcome Trust
- [ ] Invoice to British Library
- [ ] Invoice to Fuel
- [ ] Newsletter - August #74 
- [ ] Newsletter - September #78 
- [ ] Write RA job description
  * Waiting on admin response
- [x] Survey for research fellows office hours -- see #81 
- [x] Coordinate Data Blitz for CamNeuro
  * Next step (after 5th September) - merge presentations together
- [x] Doodle for Neurohackweek advisory meeting
- [ ] DBS check with [STEM Ambassadors](https://www.stem.org.uk/stem-ambassadors/ambassadors)
- [ ] Email MB re DAT project
- [ ] Email CH re FA
- [x] Introduce AM & VL
- [ ] Email SV re TFL data study group/hackathon

#### NSPN Analyses
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good
- [ ] Incorporate [von Economo atlas](http://www.dutchconnectomelab.nl/economo/) in NSPN code
- [ ] Send HCP parcellation data to JS ***deadline 1st August***
- [ ] Email to SW & PV re analysis update

#### NSPN Data Management ([issue list](https://github.com/TeamNSPN/DataManagement/issues))
- [ ] Update data management team on Cambridge repository -- see [NSPN-DM-#1](https://github.com/TeamNSPN/DataManagement/issues/1)
- [ ] Arrange date for next data management meeting
  * 👉 Email sent 31st August

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Call for evidence -- see #76 
- [x] Apply for rOpenSci fellowship -- see #66 ***deadline 1st September***
- [x] Research report for Turing -- see #69  ***deadline 22nd August***

#### Invited talks/teaching
- [x] Talk for brainintensive -- see #65 
- [ ] Presentation for Turing grad students

#### BrainAge
- [ ] Get code installed & running
- [ ] Send questions to FL

#### OpenAdvice
- [ ] Migrate to organisation [ProjectOpenAdvice](https://github.com/ProjectOpenAdvice/projectopenadvice.github.io) & build website there: https://projectopenadvice.github.io/
- [ ] Merge jekyll pull request

#### OpenConCam
- [ ] Rearrange meeting & make to do list

### Peer Reviews
- [ ] A0029 ***deadline August 29th***
- [ ] A0030 ***deadline August 30th***

### MozFest
- [x] Read through spreadsheet & categorise
- [x] Coordinate wrangler top 10 options
- [ ] Final proposals selection ***deadline September 5th***
- [ ] Onboard new team members
- [ ] Come up with plan for next few weeks

**Comment by KirstieJane** [comment]
Email MB re: dat project

**Comment by KirstieJane** [comment]
Introduce AM & VL

**Comment by KirstieJane** [comment]
Email TN re: logistics

**Comment by KirstieJane** [comment]
Email CH re: FA

**Comment by KirstieJane** [comment]
TFL data study group - hackathon
