### ISSUE TITLE
Kirstie's To Do list - Week starting 4th September 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#85]
## URGENT
- [ ] Letters of recommendation for SRA application ***deadline 26th July***

#### Emails/Online
- [ ] Email NCH re inclusivity call
- [ ] Add ICON2017 slides to whitakerlab.github.io
- [ ] Reply to PB email about outreach
- [ ] Introduce HQ to CSAP folk & Inga
- [ ] Schedule call w Wellcome Trust
- [ ] Invoice to British Library
- [ ] Invoice to Fuel
- [ ] Newsletter - September #78 
- [x] Write RA job description
  * Waiting on admin response
- [ ] Survey for research fellows office hours -- see #81 
  * Next step (after 8th September) - write summary report
- [x] Coordinate Data Blitz for CamNeuro
- [ ] Add Data Blitz & NNHD to whitaker lab blog
- [ ] DBS check with [STEM Ambassadors](https://www.stem.org.uk/stem-ambassadors/ambassadors)
- [ ] Email TN re PhD
- [ ] Email MB re DAT project
- [ ] Email CH re FA
- [ ] Email SV re TFL data study group/hackathon
- [x] Call LV re NSPN RA
- [x] Selection for Mozilla Leadership
- [x] Introduce PH to BIDS team for [reproducibility event at Birmingham](http://www.sbirc.ed.ac.uk/cyril/ReproducibleNeuroImaging.html)
- [ ] Add talk for Online Brain Intensive to website
- [ ] Reviews for D&S fundings ***deadlines 18th September***
- [ ] Add ECNP talk to website

#### NSPN Analyses
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good
- [ ] Incorporate [von Economo atlas](http://www.dutchconnectomelab.nl/economo/) in NSPN code
- [ ] Send HCP parcellation data to JS ***deadline 1st August***
- [ ] Email to SW & PV re analysis update

#### NSPN Data Management ([issue list](https://github.com/TeamNSPN/DataManagement/issues))
- [ ] Update data management team on Cambridge repository -- see [NSPN-DM-#1](https://github.com/TeamNSPN/DataManagement/issues/1)
- [ ] Arrange date for next data management meeting
  * 👉 Email sent 31st August
- [x] Reply to email questions w GP & LV
- [ ] Add to issues in [DataManagement](https://github.com/TeamNSPN/DataManagement) repo 
- [ ] Create agenda for next meeting

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Call for evidence -- see #76 ***deadline 15th September 2017***

#### Invited talks/teaching
- [ ] Presentation for Turing grad students ***deadline 4th September 2017***
- [x] Talk for ECNP ***deadline 5th September 2017***
- [ ] Abstract & bio for talk in Leeds
- [ ] Talk for Warsaw brainhack -- see #80 

#### BrainAge
- [ ] Get code installed & running
- [ ] Send questions to FL

#### OpenAdvice
- [ ] Migrate to organisation [ProjectOpenAdvice](https://github.com/ProjectOpenAdvice/projectopenadvice.github.io) & build website there: https://projectopenadvice.github.io/
- [ ] Merge jekyll pull request

#### OpenConCam
- [ ] Rearrange meeting & make to do list
- [ ] Reply to emails & update

### Peer Reviews
- [ ] A0029 ***deadline August 29th***
- [ ] A0030 ***deadline August 30th***

### MozFest
- [x] Final proposals & stipends selection ***deadline September 5th***
- [x]  Onboard new team members
- [x] Come up with plan for next few weeks

### OHBM
- [ ] OpenScience github repo
- [ ] Guide for rotating curation of slack

**Comment by KirstieJane** [comment]
Ohbm open science SIG GitHub repo

Guide for welcoming people to brainhack slack

**Comment by KirstieJane** [comment]
MozFest stipends

**Comment by KirstieJane** [comment]
Email to GP re Cambridge repository 
Call LV
Pictures to DG re data blitz

**Comment by KirstieJane** [comment]
OpenConCam satellite event

**Comment by KirstieJane** [comment]
Response for OHBM student post doc SIG on activities for precious year

**Comment by KirstieJane** [comment]
Closed with, as usual, billions of things still to do 😜
