### ISSUE TITLE
Kirstie's To Do list - Week starting 19th September 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#90]
## URGENT
- [x] Letters of recommendation for SRA application ***deadline 26th July***
- [x] Reviews for D&S fundings ***deadlines 18th September***
- [x] Review applications for student postdoc SIG ***deadline 24th September***
- [ ] Visa for China

#### Emails/Online
- [ ] Email NCH re inclusivity call
- [ ] Add ICON2017 slides to whitakerlab.github.io
- [ ] Reply to PB email about outreach
- [ ] Introduce HQ to CSAP folk & Inga
- [ ] Schedule call w Wellcome Trust
- [ ] Invoice to British Library
- [ ] Invoice to Fuel
- [ ] Newsletter - September #78 
- [x] Write RA job description
  * Waiting on admin response
- [ ] Survey for research fellows office hours -- see #81 
  * Next step (after 8th September) - write summary report
- [ ] Add CamNeuro Data Blitz & NNHD to whitaker lab blog
- [ ] DBS check with [STEM Ambassadors](https://www.stem.org.uk/stem-ambassadors/ambassadors)
- [x] Email TN re PhD
- [ ] Email MB re DAT project
- [ ] Email CH re FA
- [ ] Email SV re TFL data study group/hackathon
- [ ] Email psychiatry dude from CamNeuro NNHD
- [ ] Add talk for Online Brain Intensive to website
- [ ] Add ECNP talk to website
- [ ] Email FV & MOR re: building interactive version of r code
- [ ] Outreach prep for teaching in Peterborough

#### NSPN Analyses
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good
- [ ] Incorporate [von Economo atlas](http://www.dutchconnectomelab.nl/economo/) in NSPN code
- [ ] Send HCP parcellation data to JS ***deadline 1st August***
- [ ] Email to SW & PV re analysis update

#### NSPN Data Management ([issue list](https://github.com/TeamNSPN/DataManagement/issues))
- [ ] Update data management team on Cambridge repository -- see [NSPN-DM-#1](https://github.com/TeamNSPN/DataManagement/issues/1)
- [x] Arrange date for next data management meeting
  * 👉 Email sent 31st August
- [ ] Add replies to email questions w GP & LV to repo
- [ ] Add to issues in [DataManagement](https://github.com/TeamNSPN/DataManagement) repo 
- [ ] Create agenda for next meeting

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla

#### Invited talks/teaching
- [ ] Presentation for Turing grad students ***deadline 4th September 2017***
- [ ] Abstract & bio for talk in Leeds
- [ ] Talk for Warsaw brainhack -- see #80 

#### BrainAge
- [ ] Get code installed & running
- [ ] Send questions to FL

#### OpenAdvice
- [ ] Migrate to organisation [ProjectOpenAdvice](https://github.com/ProjectOpenAdvice/projectopenadvice.github.io) & build website there: https://projectopenadvice.github.io/
- [ ] Merge jekyll pull request

#### OpenConCam
- [ ] Rearrange meeting & make to do list
- [ ] Reply to emails & update

### Peer Reviews
- [ ] A0030 ***deadline August 30th***

### MozFest
- [ ] Create schedule
- [x] Follow up on missing facilitator emails

### OHBM
- [ ] OpenScience github repo
- [ ] Guide for rotating curation of slack

**Comment by KirstieJane** [comment]
Closing w billions of things left undone, as is the way of things 😉
