### ISSUE TITLE
Kirstie's To Do list - Week starting 25th September 2017 

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#93]
## URGENT
- [x] Visa for China ***appointment on Thursday***
- [ ] DBS check with [STEM Ambassadors](https://www.stem.org.uk/stem-ambassadors/ambassadors)
- [ ] Report number of MRI scans ***deadline 25th September***
- [x] Talk for OSIP2017 & OSET2017
  * Abstract here: [Open Science in Practice Summer School](https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/master/Kirstie-Whitaker/abstracts_bios_2017.md#open-science-in-practice-summer-school)
- [x] Bio for Dept Psychiatry -- see #77 ***deadline ages ago***

#### Emails/Online
- [ ] Email NCH re inclusivity call
- [ ] Reply to PB email about outreach
- [ ] Introduce HQ to CSAP folk & Inga
- [ ] Schedule call w Wellcome Trust
- [ ] Email MB re DAT project
- [ ] Email CH re FA
- [ ] Email SV re TFL data study group/hackathon
- [ ] Email psychiatry dude from CamNeuro NNHD
- [ ] Email FV & MOR re: building interactive version of r code

#### Paperwork
- [ ] Invoice to British Library
- [ ] Invoice to Fuel

#### Turing Community
- [ ] Survey for research fellows office hours -- see #81 
  * Next step (after 8th September) - write summary report
- [ ] Add diversity agenda item to events meeting
- [ ] Reproducible research summary email to students (& wider)
- [ ] Review events applications

#### Whitaker Lab website/github
- [ ] Newsletter - September #78 
- [ ] Add ICON2017 slides to whitakerlab.github.io
- [ ] Add CamNeuro Data Blitz & NNHD to whitaker lab blog
- [ ] Add talk for Online Brain Intensive to website
- [ ] Add ECNP talk to website
- [ ] Add OSIP & OSET talks to website

#### Outreach
- [ ] Outreach prep for teaching in Peterborough

#### NSPN Analyses
- [ ] Figure our running SW's code
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good

#### NSPN Data Management ([issue list](https://github.com/TeamNSPN/DataManagement/issues))
- [ ] Update data management team on Cambridge repository -- see [NSPN-DM-#1](https://github.com/TeamNSPN/DataManagement/issues/1)
- [ ] Add replies to email questions w GP & LV to repo
- [ ] Add to issues in [DataManagement](https://github.com/TeamNSPN/DataManagement) repo 
- [ ] Create agenda for next meeting
- [x] Slide for Ed ***deadline 29th September***

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Comments on grant w AV
- [ ] Comments on grant w LR

#### Invited talks/teaching
- [x] Presentation for Turing grad students ***deadline 4th September 2017***
- [ ] Abstract & bio for talk in Leeds
- [ ] Talk for Warsaw brainhack -- see #80 

#### BrainAge
- [ ] Get code installed & running
- [ ] Send questions to FL

#### OpenAdvice
- [ ] Migrate to organisation [ProjectOpenAdvice](https://github.com/ProjectOpenAdvice/projectopenadvice.github.io) & build website there: https://projectopenadvice.github.io/
- [ ] Merge jekyll pull request

#### OpenConCam
- [ ] Rearrange meeting & make to do list
- [ ] Reply to emails & update

### Peer Reviews
- [ ] A0030 ***deadline August 30th***
- [ ] A0032 ***deadline October 9th***

### MozFest
- [ ] Create schedule
- [ ] Create agenda for call

### OHBM
- [ ] OpenScience github repo
- [ ] Guide for rotating curation of slack

**Comment by KirstieJane** [comment]
Trend in Africa & Trust - HPC in Africa

**Comment by KirstieJane** [comment]
Closed
