### ISSUE TITLE
Kirstie's To Do list - Week starting 2nd October 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#97]
## URGENT
- [ ] DBS check with [STEM Ambassadors](https://www.stem.org.uk/stem-ambassadors/ambassadors)
- [ ] Report number of MRI scans ***deadline 25th September***
- [ ] Update Whitakerlab onboarding

#### Emails/Online
- [ ] Email NCH re inclusivity call
- [ ] Reply to PB email about outreach
- [ ] Introduce HQ to CSAP folk & Inga
- [ ] Schedule call w Wellcome Trust
- [ ] Email MB re DAT project
- [ ] Email CH re FA
- [ ] Email SV re TFL data study group/hackathon
- [ ] Email psychiatry dude from CamNeuro NNHD
- [ ] Email FV & MOR re: building interactive version of r code
- [ ] Email Trend in Africa & Trust - HPC in Africa
- [x] Sentence about how great CamNeuro is to DG

#### Paperwork
- [ ] Invoice to British Library
- [ ] Invoice to Fuel
- [x] Reimbursements for Paris talk

#### Turing Community
- [ ] Summary & next steps for research fellows office hours -- see #81 
- [x] Add diversity agenda item to events meeting
- [ ] Reproducible research summary email to students (& wider)
- [x] Review events applications

#### Whitaker Lab website/github
- [ ] Newsletter - September #78 
- [ ] Add ICON2017 slides to whitakerlab.github.io
- [ ] Add CamNeuro Data Blitz & NNHD to whitaker lab blog
- [ ] Add talk for Online Brain Intensive to website
- [ ] Add ECNP talk to website
- [ ] Add OSIP & OSET talks to website -- http://go.epfl.ch/aFD, https://library.epfl.ch/open-science-evening-talks
- [ ] Add Turing fellowship application to website
- [ ] Blog post about how to run a data blitz

#### Outreach
- [ ] Outreach prep for teaching in Peterborough

#### NSPN Analyses
- [ ] Figure our running SW's code
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good

#### NSPN Data Management ([issue list](https://github.com/TeamNSPN/DataManagement/issues))
- [ ] Update data management team on Cambridge repository -- see [NSPN-DM-#1](https://github.com/TeamNSPN/DataManagement/issues/1)
- [ ] Add replies to email questions w GP & LV to repo
- [ ] Add to issues in [DataManagement](https://github.com/TeamNSPN/DataManagement) repo 
- [ ] Create agenda for next meeting

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Comments on grant w AV
- [ ] Comments on grant w LR

#### Invited talks/teaching
- [ ] Abstract & bio for talk in Leeds
- [ ] Talk for Warsaw brainhack -- see #80 
- [ ] Talk for ICHBD in Nanning

#### BrainAge
- [ ] Talk with Turing folk about predicting age

#### OpenConCam
- [ ] Write publicity blurb

### Peer Reviews
- [ ] A0030 ***deadline August 30th***
- [ ] A0032 ***deadline October 9th***

### MozFest
- [x] Create schedule
- [ ] Email schedule to facilitators
- [ ] Check that everyone is on the google groups list

### OHBM
- [ ] OpenScience github repo
- [ ] Guide for rotating curation of slack
- [x] Short list student/postdoc applicants & sign up for interviews

### Turing Data Study group
- [ ] Coordinate facilitator training plan ***deadline 19th October***
