### ISSUE TITLE
Kirstie's To Do list - Week starting 30th October 2017

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#99]
## URGENT
- [x] Outreach prep for teaching in Peterborough
- [x] DSG: Feedback on recruitment email
- [x] Email with AL re: fellowship app
- [ ] Feedback on SPARC-EU write up
- [ ] Pay for Isla's hotel at OpenCon
- [ ] Feedback for Mozilla interview (from ages ago)

#### Emails/Online
- [ ] Email CH re FA
- [ ] Email SV re TFL data study group/hackathon
- [ ] Email psychiatry dude from CamNeuro NNHD
- [ ] Email FV & MOR re: building interactive version of r code
- [x] Feedback to EC on open canvas

#### Paperwork
- [ ] Invoice to British Library
- [ ] Invoice to Fuel

#### Turing Community
- [ ] Summary & next steps for research fellows office hours -- see #81 
- [ ] Reproducible research summary email to students (& wider)
- [ ] Paragraph about imporance of open source for website

#### Whitaker Lab website/github
- [ ] Newsletter - September #78 
- [ ] Add ICON2017 slides to whitakerlab.github.io
- [ ] Add CamNeuro Data Blitz & NNHD to whitaker lab blog
- [ ] Add talk for Online Brain Intensive to website
- [ ] Add ECNP talk to website
- [ ] Add OSIP & OSET talks to website -- http://go.epfl.ch/aFD, https://library.epfl.ch/open-science-evening-talks
- [ ] Add Turing fellowship application to website
- [ ] Blog post about how to run a data blitz
- [ ] Update Whitakerlab onboarding

#### Outreach
- [ ] DBS check with [STEM Ambassadors](https://www.stem.org.uk/stem-ambassadors/ambassadors)
- [ ] Session update for peterborough teaching
- [ ] Question slides for next week's outreach teachers
- [ ] Pass on questions for brain game
- [ ] Submit reimbursement receipts

#### NSPN Analyses
- [ ] Figure our running SW's code
- [ ] Run longitudinal pipeline on HPHI
  - [ ] Need to be able to actually run code on HPHI first! See #39 😕 
  - [ ] Need to copy over the data from HPC
  - [ ] Also need to check that everything looks good

#### NSPN Data Management ([issue list](https://github.com/TeamNSPN/DataManagement/issues))
- [ ] Update data management team on Cambridge repository -- see [NSPN-DM-#1](https://github.com/TeamNSPN/DataManagement/issues/1)
- [ ] Add replies to email questions w GP & LV to repo
- [ ] Add to issues in [DataManagement](https://github.com/TeamNSPN/DataManagement) repo 
- [ ] Create agenda for next meeting
- [ ] Send minutes from last meeting

#### Blogs/interviews/writing
- [ ] Edit story engine for Mozilla
- [ ] Comments on grant w AV
- [ ] Comments on grant w LR

#### Invited talks/teaching
- [ ] Abstract & bio for talk in Leeds
- [ ] Talk for Warsaw brainhack -- see #80 
  - [ ] Pick battle song for before the talk!
- [ ] Abstract & bio for talk at Crick
- [ ] Promote Inferior discussion
- [ ] Slides for Engaging Researchers in Good Data Management in Cambridge

#### BrainAge
- [ ] Write code to compare a bunch of different models

#### OpenConCam
- [ ] Bit more promotion

### MozFest
- [ ] Thank you emails - team & facilitators

### OHBM
- [ ] OpenScience github repo
- [ ] Guide for rotating curation of slack
- [ ] Proposal for monthly demos

### Turing Data Study group
- [x] Edit application form
- [ ] Coordinate facilitator training plan
- [ ] Write up tasks that need to be distributed to challenge teams 
- [ ] Create github repository templates for projects to support the teams

### BIDS
- [ ] Reply to emails re: making more welcoming & updating website

#### DAS
- [ ] Assign articles to ontology
- [ ] Create descriptive plots

**Comment by KirstieJane** [comment]
https://github.com/singularityware/singularityware.github.io/issues/142#issuecomment-341777852

**Comment by KirstieJane** [comment]
Send pictures from China & thank you emails
